// Copyright 2026 Latere AI.
// Licensed under the MIT License.

// Package golangci renders the org's golangci-lint configuration.
//
// golangci-lint has no configuration inheritance -- its v2 schema rejects an
// `extends` key outright -- so a shared config cannot be referenced. It has to
// be produced. Every repository's file was byte-identical apart from
// goimports' local-prefixes, which is just the module path, so there was
// nothing repo-specific being duplicated: only the duplication.
//
// The file is generated into the repository rather than kept out of it, so
// editors and IDEs still find it where they look, and a check fails when the
// committed copy no longer matches what this renders. That is the difference
// between one source of truth and four copies that agree today.
package golangci

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"latere.ai/x/ci-gate/internal/config"
)

// Name is the file every consumer repo carries at its root.
const Name = ".golangci.yml"

const header = `# Generated by lateregate. Do not edit.
#
# golangci-lint cannot inherit a shared configuration, so this file is rendered
# from latere.ai/x/ci-gate and checked by ` + "`make lint-config`" + `. Change the
# shared template there, or the disabled fixers in .lateregate.yaml, and run:
#
#	go tool lateregate golangci -write
`

// Render returns the configuration for a module.
//
// disable comes from .lateregate.yaml, the same list the `go fix` gate reads:
// golangci-lint's modernize linter and the toolchain's fixers are the same
// analyzers, so a fixer turned off for one and left on for the other is a
// repository disagreeing with itself.
func Render(module string, disable []string) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString(`
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    # modernize reports hand-written code that a standard library call or a
    # language builtin already covers: membership loops that are
    # slices.Contains, if/else pairs that are min/max, map loops that are
    # maps.Copy, HasPrefix/TrimPrefix pairs that are strings.CutPrefix.
    #
    # ` + "`make lint-modernize`" + ` runs the toolchain's own fixers on top of this;
    # they overlap but each carries checks the other does not.
    - modernize
`)
	if len(disable) > 0 {
		b.WriteString(`  settings:
    modernize:
      # Disabled in .lateregate.yaml, which the go fix gate reads too, so both
      # run the same set.
      disable:
`)
		for _, d := range disable {
			fmt.Fprintf(&b, "        - %s\n", d)
		}
	}
	b.WriteString(`
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - ` + module + "\n")
	return b.String()
}

// Check reports whether the committed file matches what Render produces.
func Check(root string, cfg *config.Config, goBin string) error {
	want, err := want(root, cfg, goBin)
	if err != nil {
		return err
	}
	path := filepath.Join(root, Name)
	got, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("%s does not exist; run `go tool lateregate golangci -write`", Name)
		}
		return err
	}
	if string(got) != want {
		return fmt.Errorf("%s no longer matches the shared configuration; "+
			"run `go tool lateregate golangci -write` to restore it, or change "+
			"the template in ci-gate if the whole org should move", Name)
	}
	return nil
}

// Write renders the file into the repository.
func Write(root string, cfg *config.Config, goBin string) (string, error) {
	want, err := want(root, cfg, goBin)
	if err != nil {
		return "", err
	}
	path := filepath.Join(root, Name)
	if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func want(root string, cfg *config.Config, goBin string) (string, error) {
	module, err := ModulePath(goBin, root)
	if err != nil {
		return "", err
	}
	return Render(module, cfg.Modernize.Disable), nil
}

// ModulePath reads the module path, which is the only part of the
// configuration that legitimately differs between repositories.
func ModulePath(goBin, dir string) (string, error) {
	cmd := exec.Command(goBin, "list", "-m")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("cannot read the module path: %w", err)
	}
	m := strings.TrimSpace(string(out))
	// Outside a module `go list -m` prints "command-line-arguments" and exits
	// zero, so the status cannot be trusted. Writing that into the config
	// would produce a file that lints and means nothing.
	if m == "" || m == "command-line-arguments" {
		return "", fmt.Errorf("%s is not inside a Go module, so there is no module path "+
			"for goimports to group against", dir)
	}
	return m, nil
}
