// Copyright 2026 Latere AI.
// Licensed under the MIT License.

// Package golangci renders the org's golangci-lint configuration.
//
// golangci-lint has no configuration inheritance -- its v2 schema rejects an
// `extends` key outright -- so a shared config cannot be referenced. It has to
// be produced. Every repository's file was byte-identical apart from
// goimports' local-prefixes, which is just the module path, so there was
// nothing repo-specific being duplicated: only the duplication.
//
// The file is rendered to the repository root rather than to a temporary
// path, so editors and IDEs find it where they look. It is not committed:
// regenerating it on every run makes drift impossible, where a committed copy
// would only make drift detectable. Consumers gitignore it, and Check fails if
// one is tracked.
package golangci

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"latere.ai/x/ci-gate/internal/config"
)

// Name is the file every consumer repo carries at its root.
const Name = ".golangci.yml"

const header = `# Generated by lateregate. Do not edit, and do not commit.
#
# golangci-lint cannot inherit a shared configuration, so this file is rendered
# from latere.ai/x/ci-gate on every run of ` + "`make lint-config`" + `. It is
# gitignored: the copy on disk is always what the shared template says, so
# there is no drift to detect.
#
# To change it, change the template in ci-gate, or the disabled fixers in this
# repository's .lateregate.yaml.
`

// Render returns the configuration for a module.
//
// disable comes from .lateregate.yaml, the same list the `go fix` gate reads:
// golangci-lint's modernize linter and the toolchain's fixers are the same
// analyzers, so a fixer turned off for one and left on for the other is a
// repository disagreeing with itself.
func Render(module string, disable []string, sl *config.Sloglint) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString(`
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    # The standard set. errcheck is the one with teeth: turning it on across
    # four repositories surfaced 452 discarded errors, and among them a lock
    # file left empty so its holder could not be named, a truncated weight
    # copy reported as success, a partial mirror published as complete, and
    # telemetry shutdown failures indistinguishable from a clean exit.
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # modernize reports hand-written code that a standard library call or a
    # language builtin already covers: membership loops that are
    # slices.Contains, if/else pairs that are min/max, map loops that are
    # maps.Copy, HasPrefix/TrimPrefix pairs that are strings.CutPrefix.
    #
    # ` + "`make lint-modernize`" + ` runs the toolchain's own fixers on top of this;
    # they overlap but each carries checks the other does not.
    - modernize
    # depguard carries one org rule: the standard library's testing package is
    # the only test framework here.
    - depguard
`)
	if sl != nil {
		b.WriteString(`    # sloglint requires the *Context variant of every slog call on a request
    # path, so the otelslog bridge can attach a trace and span id. Scoped
    # below: off the request path there is no trace to correlate with.
    - sloglint
`)
		b.WriteString("  exclusions:\n    rules:\n")
		fmt.Fprintf(&b, "      - path-except: %s\n        linters:\n          - sloglint\n", sl.RequestPaths)
		for _, e := range sl.Exempt {
			fmt.Fprintf(&b, "      - path: %s\n        linters:\n          - sloglint\n", e)
		}
	}
	b.WriteString("  settings:\n")
	if len(disable) > 0 {
		b.WriteString(`    modernize:
      # Disabled in .lateregate.yaml, which the go fix gate reads too, so both
      # run the same set.
      disable:
`)
		for _, d := range disable {
			fmt.Fprintf(&b, "        - %s\n", d)
		}
	}
	b.WriteString(`    depguard:
      rules:
        no-testify:
          # The subpackages are listed, not just the root: a deny on the module
          # path alone leaves it to depguard's prefix matching, and the rule is
          # too cheap to make anyone verify that.
          deny:
            - pkg: github.com/stretchr/testify
              desc: "use the standard library's testing package"
            - pkg: github.com/stretchr/testify/assert
              desc: "use the standard library's testing package"
            - pkg: github.com/stretchr/testify/require
              desc: "use the standard library's testing package"
            - pkg: github.com/stretchr/testify/suite
              desc: "use the standard library's testing package"
`)
	if sl != nil {
		fmt.Fprintf(&b, "    sloglint:\n      context: %s\n", sl.Context)
	}
	b.WriteString(`
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - ` + module + "\n")
	return b.String()
}

// Own reports the reason a repository keeps its own configuration, having
// checked that the file it claims to keep exists. A declared exception that
// points at nothing is a repository that lost its config and did not notice.
func Own(root string, cfg *config.Config) (string, error) {
	reason := strings.TrimSpace(cfg.Golangci.Own)
	if reason == "" {
		return "", nil
	}
	if _, err := os.Stat(filepath.Join(root, Name)); err != nil {
		return "", fmt.Errorf("golangci.own says this repository keeps its own %s, and there is none: %w", Name, err)
	}
	return reason, nil
}

// Write renders the file into the repository, replacing whatever is there.
//
// It refuses to write over a tracked file. A generated config that is also
// committed is the shape this design exists to avoid: two sources of truth
// that agree until one of them is edited.
func Write(root string, cfg *config.Config, goBin string) (string, error) {
	if tracked(root) {
		return "", fmt.Errorf("%s is tracked by git; this file is generated and must be "+
			"gitignored:\n\tgit rm --cached %s\n\techo %s >> .gitignore", Name, Name, Name)
	}
	want, err := want(root, cfg, goBin)
	if err != nil {
		return "", err
	}
	path := filepath.Join(root, Name)
	if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// tracked reports whether git has the file under version control. A repository
// that is not a git checkout at all is not tracking it.
func tracked(root string) bool {
	cmd := exec.Command("git", "ls-files", "--error-unmatch", Name)
	cmd.Dir = root
	return cmd.Run() == nil
}

func want(root string, cfg *config.Config, goBin string) (string, error) {
	module, err := ModulePath(goBin, root)
	if err != nil {
		return "", err
	}
	return Render(module, cfg.Modernize.Disable, cfg.Golangci.Sloglint), nil
}

// ModulePath reads the module path, which is the only part of the
// configuration that legitimately differs between repositories.
func ModulePath(goBin, dir string) (string, error) {
	cmd := exec.Command(goBin, "list", "-m")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("cannot read the module path: %w", err)
	}
	m := strings.TrimSpace(string(out))
	// Outside a module `go list -m` prints "command-line-arguments" and exits
	// zero, so the status cannot be trusted. Writing that into the config
	// would produce a file that lints and means nothing.
	if m == "" || m == "command-line-arguments" {
		return "", fmt.Errorf("%s is not inside a Go module, so there is no module path "+
			"for goimports to group against", dir)
	}
	return m, nil
}
