// SPDX-FileCopyrightText: 2026 Latere AI
// SPDX-License-Identifier: MIT

// Package golangci renders the org's golangci-lint configuration.
//
// golangci-lint has no configuration inheritance -- its v2 schema rejects an
// `extends` key outright -- so a shared config cannot be referenced. It has to
// be produced. Every repository's file was byte-identical apart from
// goimports' local-prefixes, which is just the module path, so there was
// nothing repo-specific being duplicated: only the duplication.
//
// The file is rendered to the repository root rather than to a temporary
// path, so editors and IDEs find it where they look. It is not committed:
// regenerating it on every run makes drift impossible, where a committed copy
// would only make drift detectable. Consumers gitignore it, and Check fails if
// one is tracked.
package golangci

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/goccy/go-yaml"

	"latere.ai/x/ci-gate/internal/config"
)

// Name is the file every consumer repo carries at its root.
const Name = ".golangci.yml"

const header = `# Generated by lateregate. Do not edit, and do not commit.
#
# golangci-lint cannot inherit a shared configuration, so this file is rendered
# from latere.ai/x/ci-gate on every run of ` + "`make lint-config`" + `. It is
# gitignored: the copy on disk is always what the shared template says, so
# there is no drift to detect.
#
# To change it, change the template in ci-gate, or the disabled fixers in this
# repository's .lateregate.yaml.
`

// Render returns the configuration for a module.
//
// disable comes from .lateregate.yaml, the same list the `go fix` gate reads:
// golangci-lint's modernize linter and the toolchain's fixers are the same
// analyzers, so a fixer turned off for one and left on for the other is a
// repository disagreeing with itself.
//
// extra is merged over the shared set, so a repository with lint policy of its
// own keeps it in .lateregate.yaml rather than in a second file.
func Render(module string, disable []string, sl *config.Sloglint, extra map[string]any) (string, error) {
	// The three parts of `linters` are built as typed locals and assembled at
	// the end. Reaching back into an assembled map[string]any to add a key
	// means asserting its type on every touch, and an assertion that is wrong
	// panics rather than failing the gate.
	//
	// The standard set, plus the linters that catch bugs rather than style.
	// This is the org's bar: a repository may add to it through
	// golangci.extra, never subtract.
	//
	// Left out deliberately: revive's exported rule is a documentation
	// project (265 findings across the org), and gosec and misspell encode
	// facts about one repository -- which directories may be world-readable,
	// which British spellings are deliberate -- that no shared set can carry.
	enable := []any{
		"errcheck", "govet", "ineffassign", "staticcheck", "unused",
		"modernize", "depguard",
		"bodyclose",     // an unclosed response body leaks a connection
		"errorlint",     // %w and errors.Is/As used correctly across wrapping
		"nilerr",        // returning nil after a non-nil error
		"sqlclosecheck", // rows and statements closed
		"rowserrcheck",
		"noctx",        // a request without a context cannot be canceled
		"contextcheck", // and one that drops the caller's context ignores it
		"errchkjson",
		"durationcheck",
		"copyloopvar",
		"unconvert",
		"wastedassign",
	}

	settings := map[string]any{
		"depguard": map[string]any{
			"rules": map[string]any{
				"no-testify": map[string]any{"deny": denyTestify()},
				"stdlib":     stdlibRule(),
			},
		},
		// A type assertion whose second result is dropped panics on the value
		// it was written to handle, and errcheck ignores it by default.
		"errcheck": map[string]any{"check-type-assertions": true},
		"govet":    govetSettings(),
		"staticcheck": map[string]any{
			// Everything except the documentation-comment style checks, which
			// judge comment wording rather than correctness. The list is
			// explicit so an upgrade is a reviewable edit rather than a
			// silent change of which rules apply.
			"checks": []any{
				"all", "-ST1000", "-ST1003", "-ST1016",
				"-ST1020", "-ST1021", "-ST1022",
			},
		},
	}
	if len(disable) > 0 {
		ds := make([]any, 0, len(disable))
		for _, d := range disable {
			ds = append(ds, d)
		}
		settings["modernize"] = map[string]any{"disable": ds}
	}

	// Tests exercise error paths deliberately, read fixture files by
	// constructed path, and marshal literals written a line earlier. None of
	// that is a finding there, and replichai's config had already argued so.
	//
	// bodyclose is here for a different reason: it analyses the call site and
	// does not follow into helpers, and a test suite is built out of helpers.
	// Measured on service-template, all 33 of its findings were wrong -- 29
	// were httptest recorder results, whose Body is a NopCloser over a byte
	// slice with no connection to leak, and the other 4 were real client
	// responses that the helper already closed with defer. A linter that is
	// wrong every time it fires teaches people to stop reading it.
	exclusionRules := []any{
		map[string]any{
			"path":    `_test\.go`,
			"linters": []any{"errcheck", "noctx", "errchkjson", "bodyclose"},
		},
	}

	if sl != nil {
		enable = append(enable, "sloglint")
		settings["sloglint"] = map[string]any{"context": sl.Context}
		exclusionRules = append(exclusionRules, map[string]any{
			"path-except": sl.RequestPaths,
			"linters":     []any{"sloglint"},
		})
		for _, e := range sl.Exempt {
			exclusionRules = append(exclusionRules,
				map[string]any{"path": e, "linters": []any{"sloglint"}})
		}
	}

	linters := map[string]any{
		"default":  "none",
		"enable":   enable,
		"settings": settings,
		"exclusions": map[string]any{
			// Generated code is not the repository's to fix, and neither are
			// the Go files a JavaScript package happens to carry inside a
			// frontend directory the Go tool still walks.
			"generated": "lax",
			"paths":     []any{`(^|/)node_modules/`},
			"rules":     exclusionRules,
		},
	}

	doc := map[string]any{
		"version": "2",
		"run":     map[string]any{"timeout": "5m", "tests": true},
		"linters": linters,
		// A gate reports every finding it has. The tool truncates repeated
		// findings by default, which turns a list of twenty into a list of
		// three and hides the rest until the first three are fixed, so the
		// size of the work is never visible at once.
		"issues": map[string]any{
			"max-issues-per-linter": 0,
			"max-same-issues":       0,
		},
		"formatters": map[string]any{
			"enable": []any{"gofmt", "goimports"},
			"settings": map[string]any{
				"goimports": map[string]any{"local-prefixes": []any{module}},
			},
		},
	}
	merge(doc, extra)

	body, err := yaml.Marshal(doc)
	if err != nil {
		return "", fmt.Errorf("rendering the golangci config: %w", err)
	}
	return header + "\n" + string(body), nil
}

// govetSettings turns on every analyzer and names the two left off.
//
// Enabling the set by name would mean a toolchain that adds an analyzer ships
// it disabled here, and nobody would notice which one. The two exclusions are
// judgement, not defects: fieldalignment optimizes memory layout at the cost
// of grouping related fields, and shadow flags the idiomatic
// `if err := f(); err != nil` inside a function that already holds an err.
func govetSettings() map[string]any {
	return map[string]any{
		"enable-all": true,
		"disable":    []any{"fieldalignment", "shadow"},
	}
}

// stdlibRule is the standard library choices the org fixes for every
// repository. Each denial has a replacement that is strictly better, so the
// rule costs an author nothing and keeps one answer per question in the tree.
func stdlibRule() map[string]any {
	return map[string]any{
		"list-mode": "lax",
		"files":     []any{"$all"},
		// depguard matches a denied package by prefix, so the structured
		// logging package is allowed by name to keep the "log" denial below
		// from reaching it.
		"allow": []any{"log/slog", "math/rand/v2"},
		"deny": []any{
			map[string]any{"pkg": "io/ioutil", "desc": "deprecated; use io and os"},
			map[string]any{"pkg": "math/rand", "desc": "use math/rand/v2"},
			map[string]any{"pkg": "log",
				"desc": "use log/slog; slog.NewLogLogger adapts it for http.Server.ErrorLog"},
			map[string]any{"pkg": "github.com/pkg/errors",
				"desc": "use the standard errors package with %w"},
		},
	}
}

func denyTestify() []any {
	var out []any
	// The subpackages are named, not just the module path: a deny on the root
	// alone leaves it to depguard's prefix matching, and the rule is too cheap
	// to make anyone verify that.
	for _, p := range []string{
		"github.com/stretchr/testify",
		"github.com/stretchr/testify/assert",
		"github.com/stretchr/testify/require",
		"github.com/stretchr/testify/suite",
	} {
		out = append(out, map[string]any{
			"pkg":  p,
			"desc": "use the standard library's testing package",
		})
	}
	return out
}

// merge folds src into dst. Maps merge key by key so a repository can add one
// setting without restating the block it lives in. linters.enable appends,
// because a repository adding a linter means "as well as", never "instead of"
// -- that is what keeps the shared set shared. Any other list replaces, since
// a repository redefining a rule list means exactly that.
func merge(dst, src map[string]any) {
	for k, v := range src {
		existing, ok := dst[k]
		if !ok {
			dst[k] = v
			continue
		}
		em, emOK := existing.(map[string]any)
		vm, vmOK := v.(map[string]any)
		if emOK && vmOK {
			merge(em, vm)
			continue
		}
		if k == "enable" {
			if el, ok := existing.([]any); ok {
				if vl, ok := v.([]any); ok {
					dst[k] = append(el, vl...)
					continue
				}
			}
		}
		dst[k] = v
	}
}

// Own reports the reason a repository keeps its own configuration, having
// checked that the file it claims to keep exists. A declared exception that
// points at nothing is a repository that lost its config and did not notice.
func Own(root string, cfg *config.Config) (string, error) {
	reason := strings.TrimSpace(cfg.Golangci.Own)
	if reason == "" {
		return "", nil
	}
	if _, err := os.Stat(filepath.Join(root, Name)); err != nil {
		return "", fmt.Errorf("golangci.own says this repository keeps its own %s, and there is none: %w", Name, err)
	}
	return reason, nil
}

// Write renders the file into the repository, replacing whatever is there.
//
// It refuses to write over a tracked file. A generated config that is also
// committed is the shape this design exists to avoid: two sources of truth
// that agree until one of them is edited.
func Write(root string, cfg *config.Config, goBin string) (string, error) {
	if tracked(root) {
		return "", fmt.Errorf("%s is tracked by git; this file is generated and must be "+
			"gitignored:\n\tgit rm --cached %s\n\techo %s >> .gitignore", Name, Name, Name)
	}
	want, err := want(root, cfg, goBin)
	if err != nil {
		return "", err
	}
	path := filepath.Join(root, Name)
	if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// tracked reports whether git has the file under version control. A repository
// that is not a git checkout at all is not tracking it.
func tracked(root string) bool {
	cmd := exec.CommandContext(context.Background(), "git", "ls-files", "--error-unmatch", Name)
	cmd.Dir = root
	return cmd.Run() == nil
}

func want(root string, cfg *config.Config, goBin string) (string, error) {
	module, err := ModulePath(goBin, root)
	if err != nil {
		return "", err
	}
	return Render(module, cfg.Modernize.Disable, cfg.Golangci.Sloglint, cfg.Golangci.Extra)
}

// ModulePath reads the module path, which is the only part of the
// configuration that legitimately differs between repositories.
func ModulePath(goBin, dir string) (string, error) {
	cmd := exec.CommandContext(context.Background(), goBin, "list", "-m")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("cannot read the module path: %w", err)
	}
	m := strings.TrimSpace(string(out))
	// Outside a module `go list -m` prints "command-line-arguments" and exits
	// zero, so the status cannot be trusted. Writing that into the config
	// would produce a file that lints and means nothing.
	if m == "" || m == "command-line-arguments" {
		return "", fmt.Errorf("%s is not inside a Go module, so there is no module path "+
			"for goimports to group against", dir)
	}
	return m, nil
}
